### ISSUE TITLE
About training weights

### ISSUE THREAD

**Issue by raulignac10** [attila-petho/DuckPropagation#1]
Hello @attila-petho 

First of all thank you for the knowledge shared for those of us starting to learn AI in robotics.

I have a question, to evaluate the trained model and see it in the gym-duckietown simulator with the trained weights, should I train it first ? because I tried to run some results inside the repository but it does not find the following file in the different attempts changed the hyperparameters according to what you want to evaluate

the error in one of the attempts is the following:

FileNotFoundError: [Errno 2] No such file or directory: '/home/raul/DuckPropagation/models/zigzag_dists/A2C/checkpoints/A2C_1e6steps_GrayS_FS3_DR1_heading_base/step__100000_steps.zip.zip'.

I hope you can help me

I have already started to train a base model.

Thank you very much for your help

Raúl

**Comment by attila-petho** [comment]
Hi @raulignac10 

Thanks for the feedback. It looks like I made a mistake in the test_agent.py file, which caused the error when trying to load a saved model. In the last commit I made some corrections, so now it should work properly. 

However, I should also mention, that the model you are trying to load is a checkpoint model (meaning it is not the final model saved after 1M steps, but an earlier one). I suggest setting the _load_checkpoint_ option in the _eval_config_ section to False in  the train_config.yml file before evaluation.

I also provided more information about loading checkpoint models and evaluation options in the readme file.

I hope this was helpful. Have fun with the models :)

Best wishes

Attila

**Comment by raulignac10** [comment]
Hi @attila-petho 

Thank you very much for your help, everything works great.

I have also been training models with different hyperparameters and for more than 2e6 steps, your repository is very good and very well described for learning.

Best regards

Raúl
